### ISSUE TITLE
Propuesta de roadmap

### ISSUE THREAD

**Issue by thehackermonkey** [CodeandoGuadalajara/mapeociclista#1]
### Para que este proyecto se complete identifico los siguientes pasos
- #### Contactar a red de colectivos ciclistas para proponer el proyecto y su organización en conjunto.
  - Hay que llevar una **presentación** con ejemplos de mapeo de riesgos y valor de tener estos datos disponibles de manera pública.
  - También es importante llevar la **descripción** del movimiento _hackea tu ciudad_
  -  Co-organizar la logística del evento con la organización sede.
    
    ```
       * Mobiliario (Sillas, mesas, audio y video)
       * Disponibilidad de Internet en el espacio para varias personas
       * Comida
       * Agenda (a que hora inicia, quien da la charla introductoria, el taller y el cierre)
       * Voluntarios (quien será responsable de que cosa durante el evento)
    ```
- #### Invitar personalmente a colectivos universitarios (por medio de los embajadores sería ideal) para que asistan al taller.
  - Hay que llevar la misma presentación sobre mapeo y datos. Adicionalmente se tiene que ver la forma de **replicar el mismo ejercicio para su centro universitario** de tal manera que el impacto del evento principal se distribuya en cascada hacia diversos espacios.
- #### Invitar a periodistas interesados tanto para cubrir el evento como en crear una nota con los datos recabados posteriormente

**Si están interesados en tomar ownership de alguno de estos puntos comenten sobre este issue**. Igual si creen que hace falta algo.

**Comment by basicavisual** [comment]
@jdeltoro1973 contacta periodistas. Falta quien contacte Colecitvos Ciclistas y Colectivos Universitarios.

**Comment by thehackermonkey** [comment]
Estoy contactando a **GDL en Bici**

Otro actor con el que estaría bueno acercarse es el "[Observatorio Ciudadano de Movilidad y Transporte Público de Jalisco" ](https://www.facebook.com/observatorio.ciudadano.jalisco/)

Quien tenga el contacto o se anime a conseguirlo. Dele.

**Comment by basicavisual** [comment]
Neysa y Aarón nos contactan con Ciclo CUAAD.
Yo contacto al Observatorio Ciudadano de Movilidad y Transporte.
